# Generated by Django 5.0.4 on 2024-04-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_alter_concert_venue_alter_song_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateField(),
        ),
    ]
